config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :rentals
  resources :properties
  resources :addresses
  resources :cities
  root to: 'visitors#index'
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :address
  has_one :rental
  has_one :sale
  validates_presence_of :address_id, :private_area, :public_area
  validates_numericality_of :bedrooms, only_integer: true, greater_than: 0
  validates_numericality_of :garages, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :public_area, greater_than: 0
  validates_numericality_of :private_area, greater_than: 0

  def summary
    "#{ id }, at #{ address.summary } with #{ total_area }m2"
  end

  def total_area
    private_area + public_area
  end

  def possible_addresses
    Address.all.map { |each| [each.summary, each.id] }
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  def index
    @properties = Property.all
  end

  def show
  end

  def new
    @property = Property.new
  end

  def edit
  end

  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:address_id, :bedrooms, :garages, :party_area, :private_area, :public_area, :security, :public_patio, :public_pool)
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.haml
= bootstrap_form_for @property do |f|
  .field
    = f.select :address_id, options_for_select(@property.possible_addresses, @property.address_id)
  .field
    = f.number_field :bedrooms
  .field
    = f.number_field :garages
  .field
    = f.text_field :private_area
  .field
    = f.text_field :public_area
  .field
    = f.check_box :party_area
  .field
    = f.check_box :security
  .field
    = f.check_box :public_patio
  .field
    = f.check_box :public_pool
  .actions
    .btn-group
      = f.submit 'Save'
      = link_to 'Cancel', properties_path, class: 'btn btn-danger'

app/views/properties/edit.html.haml
= content_for :heading do
  Editing property

= render 'form'

app/views/properties/index.html.haml
= content_for :heading do
  Listing properties

= link_to 'New Property', new_property_path, class: 'btn btn-primary'

%table.table
  %thead
    %tr
      %th Id
      %th Address
      %th Bedrooms
      %th Total area
      %th Actions

  %tbody
    - @properties.each do |property|
      %tr
        %td= property.id
        %td= property.address.summary
        %td= property.bedrooms
        %td= property.total_area
        %td= render 'actions_menu', paths: { show: property, edit: edit_property_path(property), delete: property } 

app/views/properties/new.html.haml
= content_for :heading do
  New property

= render 'form'

app/views/properties/show.html.haml
= content_for :heading do
  Display property
%p
  %b Address:
  = link_to @property.address.summary, @property.address
%p
  %b Bedrooms:
  = @property.bedrooms
%p
  %b Garages:
  = @property.garages
%p
  %b Private area:
  = @property.private_area
%p
  %b Public area:
  = @property.public_area
- unless @property.rental.nil?
  %p
    %b Rental price:
    = @property.rental.price
- unless @property.sale.nil?
  %p
    %b Sale price:
    = @property.sale.price
%p
  - if @property.party_area
    %span.label.label-success Party Area
  - if @property.security
    %span.label.label-success Security 
  - if @property.public_patio
    %span.label.label-success Public Patio
  - if @property.public_pool
    %span.label.label-success Public Pool 
.btn-group
  = link_to 'Edit', edit_property_path(@property), class: 'btn btn-default'
  = link_to 'Back', properties_path, class: 'btn btn-primary' 