config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :rentals
  resources :properties
  resources :addresses
  resources :cities
  root to: 'visitors#index'
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :property
  validates_presence_of :property_id
  validates_uniqueness_of :property_id
  validates_numericality_of :price, greater_than: 0
  
  def possible_properties
    Property.all.map { |each| [each.summary, each.id] }
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  def index
    @rentals = Rental.all
  end

  def show
  end

  def new
    @rental = Rental.new
  end

  def edit
  end

  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def rental_params
    params.require(:rental).permit(:property_id, :price)
  end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.haml
= bootstrap_form_for @rental do |f|
  .field
    = f.select :property_id, options_for_select(@rental.possible_properties, @rental.property_id)
  .field
    = f.text_field :price
  .actions
    .btn-group
      = f.submit 'Save'
      = link_to 'Cancel', rentals_path, class: 'btn btn-danger'

app/views/rentals/edit.html.haml
= content_for :heading do
  Editing rental

= render 'form'

app/views/rentals/index.html.haml
= content_for :heading do
  Listing rentals

= link_to 'New Rental', new_rental_path, class: 'btn btn-primary', role: 'button'  

%table.table
  %thead
    %tr
      %th Property
      %th Price
      %th Actions

  %tbody
    - @rentals.each do |rental|
      %tr
        %td= rental.property.summary
        %td= rental.price
        %td= render 'actions_menu', paths: { show: rental, edit: edit_rental_path(rental), delete: rental }

app/views/rentals/new.html.haml
= content_for :heading do
  New rental

= render 'form'

app/views/rentals/show.html.haml
= content_for :heading do
  Display rental
%p
  %b Property:
  = @rental.property.summary
%p
  %b Price:
  = @rental.price
.btn-group
  = link_to 'Edit', edit_rental_path(@rental), class: 'btn btn-default'
  = link_to 'Back', rentals_path, class: 'btn btn-primary' 