config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :rentals
  resources :properties
  resources :addresses
  resources :cities
  root to: 'visitors#index'
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :property
  validates_presence_of :property_id
  validates_uniqueness_of :property_id
  validates_numericality_of :price, greater_than: 0
  
  def possible_properties
    Property.all.map { |each| [each.summary, each.id] }
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  def index
    @sales = Sale.all
  end

  def show
  end

  def new
    @sale = Sale.new
  end

  def edit
  end

  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_sale
    @sale = Sale.find(params[:id])
  end

  def sale_params
    params.require(:sale).permit(:property_id, :price)
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.haml
= bootstrap_form_for @sale do |f|
  .field
    = f.select :property_id, options_for_select(@sale.possible_properties, @sale.property_id)
  .field
    = f.text_field :price
  .actions
    .btn-group
      = f.submit 'Save'
      = link_to 'Cancel', sales_path, class: 'btn btn-danger'

app/views/sales/edit.html.haml
= content_for :heading do
  Editing sale

= render 'form'

app/views/sales/index.html.haml
= content_for :heading do 
  Listing sales

= link_to 'New Sale', new_sale_path, class: 'btn btn-primary'
 
%table.table
  %thead
    %tr
      %th Property
      %th Price
      %th Actions

  %tbody
    - @sales.each do |sale|
      %tr
        %td= sale.property.summary
        %td= sale.price
        %td= render 'actions_menu', paths: { show: sale, edit: edit_sale_path(sale), delete: sale }

app/views/sales/new.html.haml
= content_for :heading do
  New sale

= render 'form'

app/views/sales/show.html.haml
= content_for :heading do
  Display sale
%p
  %b Property:
  = @sale.property.summary
%p
  %b Price:
  = @sale.price
.btn-group
  = link_to 'Edit', edit_sale_path(@sale), class: 'btn btn-default'
  = link_to 'Back', sales_path, class: 'btn btn-primary' 