config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :rentals
  resources :properties
  resources :addresses
  resources :cities
  root to: 'visitors#index'
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to "Cities", cities_url
%li= link_to "Addresses", addresses_url
%li= link_to "Properties", properties_url
%li= link_to "Rentals", rentals_url
%li= link_to "Sales", sales_url
%li= link_to "About", page_path('about') 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Real Estate'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Real Estate'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container
      = render 'layouts/messages'
      .page-header
        %h1= yield(:heading)
      = yield